class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start4'
        self.MirrorCommand = 'mirror4'
        self.UnzipMirrorCommand = 'unzipmirror4'
        self.TarMirrorCommand = 'tarmirror4'
        self.CancelMirror = 'cancel4'
        self.CancelAllCommand = 'cancelall4'
        self.ListCommand = 'list4555454'
        self.StatusCommand = 'status4'
        self.AuthorizeCommand = 'auth4'
        self.UnAuthorizeCommand = 'unauth4'
        self.PingCommand = 'ping4'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats4'
        self.HelpCommand = 'help4'
        self.LogCommand = 'log4'
        self.SpeedCommand = 'speedtest4'
        self.CloneCommand = 'clone4'
        self.WatchCommand = 'watch4'
        self.TarWatchCommand = 'tarw4'
        self.DeleteCommand = 'del4'
        self.UsageCommand = 'usage4'
        self.RepoCommand = 'repo4'

BotCommands = _BotCommands()
