class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start1'
        self.MirrorCommand = 'mirror1'
        self.UnzipMirrorCommand = 'unzipmirror1'
        self.TarMirrorCommand = 'tarmirror1'
        self.CancelMirror = 'cancel1'
        self.CancelAllCommand = 'cancelall1'
        self.ListCommand = 'list1'
        self.StatusCommand = 'status1'
        self.AuthorizeCommand = 'auth1'
        self.UnAuthorizeCommand = 'unauth1'
        self.PingCommand = 'ping1'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats1'
        self.HelpCommand = 'help45546456'
        self.LogCommand = 'log1'
        self.SpeedCommand = 'speedtest1'
        self.CloneCommand = 'clone1'
        self.WatchCommand = 'watch1'
        self.TarWatchCommand = 'tarw1'
        self.DeleteCommand = 'del1'
        self.UsageCommand = 'usage5'
        self.RepoCommand = 'repo0025'

BotCommands = _BotCommands()
