class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start6'
        self.MirrorCommand = 'mirror6'
        self.UnzipMirrorCommand = 'unzipmirror6'
        self.TarMirrorCommand = 'tarmirror6'
        self.CancelMirror = 'cancel6'
        self.CancelAllCommand = 'cancelall6'
        self.ListCommand = 'list6'
        self.StatusCommand = 'status6'
        self.AuthorizeCommand = 'auth6'
        self.UnAuthorizeCommand = 'unauth6'
        self.PingCommand = 'ping6'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats6'
        self.HelpCommand = 'help45546456'
        self.LogCommand = 'log6'
        self.SpeedCommand = 'speedtest6'
        self.CloneCommand = 'clone6'
        self.WatchCommand = 'watch6'
        self.TarWatchCommand = 'tarw6'
        self.DeleteCommand = 'del6'
        self.UsageCommand = 'usage6'
        self.RepoCommand = 'repo0025'

BotCommands = _BotCommands()
